# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).

{ config, lib, pkgs, ... }:

let

my-file = pkgs.writeShellScriptBin "my-awesome-script" ''
    #!/usr/bin/env bash
    echo "testing"
    cat /etc/passwd

'';

cage-startup-script = pkgs.writeShellScriptBin "cage-startup.sh" ''
  read -r url < /etc/startup-url
  ${pkgs.chromium}/bin/chromium --kiosk --start-maximized --start-fullscreen --no-first-run --noerrdialogs --disable-infobars $url
'';

# Edit this URL
  kioskUrl = "https://example.com";

  # Start script that runs AFTER weston is up
  startKiosk = pkgs.writeShellScript "start-kiosk.sh" ''
    set -euo pipefail
    read -r url < /etc/startup-url

    # Give weston a moment to create the wayland socket
    for i in $(seq 1 50); do
      [ -S "''${XDG_RUNTIME_DIR}/wayland-0" ] && break
      sleep 0.1
    done

    exec ${pkgs.chromium}/bin/chromium \
      --ozone-platform=wayland \
      --enable-features=UseOzonePlatform \
      --disable-features=WaylandWindowDecorations \
      --kiosk \
      --start-maximized \
      --no-first-run \
      --no-default-browser-check \
      --disable-infobars \
      --disable-session-crashed-bubble \
      --noerrdialogs \
      $url
  '';

  # Simple script to launch chromium (and restart it if it exits)
  kioskBrowser = pkgs.writeShellScript "kiosk-browser" ''
    set -euo pipefail
    read -r url < /etc/startup-url

    # Optional: wait a moment for sway to be ready
    sleep 0.2

      ${pkgs.chromium}/bin/chromium \
        --ozone-platform=wayland \
        --enable-features=UseOzonePlatform \
        --disable-features=WaylandWindowDecorations \
        --kiosk \
        --start-maximized \
        --no-first-run \
        --no-default-browser-check \
        --disable-infobars \
        --disable-session-crashed-bubble \
        --noerrdialogs \
        "$url" || true

  '';

  # Sway config file generated by Nix
  swayKioskConfig = pkgs.writeText "sway-kiosk.conf" ''
    ### Minimal kiosk Sway config

    # Don’t lock, don’t DPMS blank (optional)
    exec_always ${pkgs.swayidle}/bin/swayidle -w \
      timeout 0 '${pkgs.sway}/bin/swaymsg "output * dpms on"' \
      before-sleep '${pkgs.sway}/bin/swaymsg "output * dpms on"'

    # Hide mouse cursor when idle (optional)
    seat seat0 hide_cursor 1000

    # Start the browser
    exec_always ${kioskBrowser}

    # Force Chromium fullscreen (Sway can enforce it)
    for_window [app_id="chromium"] fullscreen enable
    for_window [class="Chromium"] fullscreen enable

    # Prevent accidental exit (optional)
    bindsym $mod+Shift+e nop "disabled"
    bindsym $mod+Shift+c nop "disabled"

    # Optional: allow a manual restart key if you’re debugging
    # bindsym Ctrl+Alt+r exec ${pkgs.sway}/bin/swaymsg reload

    # Minimal input defaults
    input * {
      xkb_layout us
    }

    # Output: auto
    output * {
      scale 1
    }
  '';

in

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  nixpkgs.config.allowUnfree = true;

  # Use the extlinux boot loader. (NixOS wants to enable GRUB by default)
  boot.loader.grub.enable = false;
  # Enables the generation of /boot/extlinux/extlinux.conf
  boot.loader.generic-extlinux-compatible.enable = true;

  hardware.enableAllFirmware = true;

  # networking.hostName = "nixos"; # Define your hostname.

  # Configure network connections interactively with nmcli or nmtui.
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Don't write the journal to the SD card
  # Comment this out if need to debug previous boot logs
  services.journald.storage = "volatile";

  boot.consoleLogLevel = lib.mkDefault 7;

  # The serial ports listed here are:
  # - ttyS0: for Tegra (Jetson TX1)
  # - ttyAMA0: for QEMU's -machine virt
  boot.kernelParams = [
    "console=ttyS0,115200n8"
    "console=ttyAMA0,115200n8"
    "console=tty0"
  ];

#  hardware.bluetooth.enable = false;
#  boot.blacklistedKernelModules = ["bluetooth"];


  # Set your time zone.
  # time.timeZone = "Europe/Amsterdam";

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Select internationalisation properties.
  # i18n.defaultLocale = "en_US.UTF-8";
  # console = {
  #   font = "Lat2-Terminus16";
  #   keyMap = "us";
  #   useXkbConfig = true; # use xkb.options in tty.
  # };

  # Enable the X11 windowing system.
  # services.xserver.enable = true;


  

  # Configure keymap in X11
  # services.xserver.xkb.layout = "us";
  # services.xserver.xkb.options = "eurosign:e,caps:escape";

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable sound.
  # services.pulseaudio.enable = true;
  # OR
  # services.pipewire = {
  #   enable = true;
  #   pulse.enable = true;
  # };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.libinput.enable = true;

  security.sudo.wheelNeedsPassword = false;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.revolve = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
    initialPassword = "changeme";
    packages = with pkgs; [
      tree
    ];
  };

  users.motd = ''

==================================================

  Configuration of website url can be found
  at /etc/startup-url

  To adjust the launch url do the following steps

  1. sudo vim /etc/startup-url
  2. sudo systemctl restart cage-tty1

==================================================

  '';

  # programs.firefox.enable = true;

  # List packages installed in system profile.
  # You can use https://search.nixos.org/ to find more packages (and options).
  environment.systemPackages = with pkgs; [
  #  w3m-nographics # needed for the manual anyway
    testdisk # useful for repairing boot problems
    ms-sys # for writing Microsoft boot sectors / MBRs
    efibootmgr
    efivar
    parted
    gptfdisk
    ddrescue
    ccrypt
    cryptsetup # needed for dm-crypt volumes

    # Some text editors.
    vim

    # Some networking tools.
    fuse
    fuse3
    sshfs-fuse
    socat
    screen
    tcpdump

    # Hardware-related tools.
    sdparm
    hdparm
    smartmontools # for diagnosing hard disks
    pciutils
    usbutils
    nvme-cli

    # Some compression/archiver tools.
    unzip
    zip

    # Some utilities
    jq

    # Interact with HDMI CEC
    libcec
    v4l-utils

    # Needed for Kiosk Functionality
    wget
    chromium
    sysstat
    cage-startup-script
    cage # debugging this
    libraspberrypi
    raspberrypi-eeprom
    git
    weston
    sway
    swayidle
    wl-clipboard

  ];

  # Create /etc/startup-url with default value if it doesn't exist
  systemd.tmpfiles.rules = [
    "f /etc/startup-url 0644 root root - https://tools.revolvepickleball.com/signage/courts-1-4"
  ];

  services.cage = {
    enable = false;
    user = "revolve";
    #user = "root";
    #program = "${pkgs.chromium}/bin/chromium --kiosk https://tools.revolvepickleball.com/signage/test";
    #program = "/home/revolve${cage-startup-script}";
    #program = "/home/revolve/launch.sh";
    extraArguments = [ "-d" ];
    program = "/run/current-system/sw/bin/cage-startup.sh";
    environment = {
      WLR_LIBINPUT_NO_DEVICES = "1";
    };
  };

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Open ports in the firewall.
  networking.firewall.allowedTCPPorts = [ 80 ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # Copy the NixOS configuration file and link it from the resulting system
  # (/run/current-system/configuration.nix). This is useful in case you
  # accidentally delete configuration.nix.
  # system.copySystemConfiguration = true;

  # Create a dedicated kiosk user (recommended)
  users.users.kiosk = {
    isNormalUser = true;
    extraGroups = [ "video" "input" "render" "seat" ];
    # If you want to SSH in, add your key here.
    # openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA..." ];
  };

  programs.sway.enable = true;

  #### Auto-login kiosk user on tty1
  services.getty.autologinUser = "kiosk";

  #### Optional but recommended: stop other ttys from stealing focus
  systemd.services."getty@tty1".enable = false;
  systemd.services."autovt@tty1".enable = false;

  #### Start Sway automatically for kiosk user on boot
  systemd.services.sway-kiosk = {
    description = "Sway kiosk session on tty1";
    wantedBy = [ "multi-user.target" ];
    after = [ "systemd-user-sessions.service" "network-online.target" ];
    wants = [ "network-online.target" ];

    serviceConfig = {
      User = "kiosk";
      PAMName = "login";

      # Bind to tty1
      TTYPath = "/dev/tty1";
      StandardInput = "tty";
      TTYReset = "yes";
      TTYVHangup = "yes";
      TTYVTDisallocate = "yes";

      # Environment for Wayland
      Environment = [
        "XDG_SESSION_TYPE=wayland"
        "XDG_RUNTIME_DIR=/run/user/%U"
        "WLR_NO_HARDWARE_CURSORS=1"
      ];

      Restart = "always";
      RestartSec = 2;

      # Sometimes needed for DRM/input access on embedded boxes
      SupplementaryGroups = [ "video" "input" "render" ];
    };

    script = ''
      # Ensure runtime dir exists (usually handled by pam_systemd, but safe)
      mkdir -p /run/user/$(id -u)
      chmod 700 /run/user/$(id -u)

      # Run Sway with our config
      exec ${pkgs.sway}/bin/sway --config ${swayKioskConfig}
    '';
  };

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.11"; # Did you read the comment?

}

